# Entendiendo async/await

Si no est√°s familiarizado con ECMAScript 2017, puede que no sepas acerca de `async`/`await`. Es una forma √∫til de manejar promesas de una manera ambigua. Tambi√©n es un poco m√°s r√°pido y aumenta la legibilidad.

## ¬øC√≥mo trabajan las promesas?

Antes de que podamos entrar en async/await, debes saber qu√© son las promesas y c√≥mo funcionan, porque `async`/`await` es solo una forma de manejar las promesas. Si sabe qu√© son las promesas y c√≥mo lidiar con ellas, puede omitir esta parte.  

Las promesas son una forma de manejar tareas asincr√≥nicas en JavaScript; son la alternativa m√°s nueva a los `callbacks`. Una promesa tiene muchas similitudes con una barra de progreso; representan un proceso inacabado y en curso. Un excelente ejemplo de esto es una solicitud a un servidor (por ejemplo, discord.js env√≠a solicitudes a la API de Discord).

Una promesa puede tener tres estados; pendiente, resuelto y rechazado

El estado **pendiente** significa que la promesa a√∫n est√° en curso y no se ha resuelto ni rechazado.
El estado **resuelto** significa que la promesa est√° hecha y ejecutada sin errores.
El estado **rechazado** significa que la promesa encontr√≥ un error y no se pudo ejecutar correctamente.

Una cosa importante que debes saber es que una promesa solo puede tener un estado simult√°neamente; nunca puede estar pendiente y resuelto, rechazado y resuelto, o pendiente y rechazado. Es posible que te preguntes, "¬øC√≥mo se ver√≠a eso en el c√≥digo?". Aqu√≠ hay un peque√±o ejemplo:

::: tip
Este ejemplo usa c√≥digo ES6. Si no sabes qu√© es esto, deber√≠as leerlo [aqu√≠](/informacion-adicional/sintaxis-ES6.html).
:::

```js
function deleteMessages(amount) {
	return new Promise(resolve => {
		if (amount > 10) throw new Error('No puedes eliminar m√°s de 10 mensajes a la vez.');
		setTimeout(() => resolve(`Se han eliminado ${amount} mensajes.`), 2000);
	});
}

deleteMessages(5).then(value => {
	// `deleteMessages` se ha completado y no ha ocurrido ning√∫n error
	// El valor resuelto ser√° la cadena de texto "Se han eliminado 5 mensajes."
}).catch(error => {
	// `deleteMessages` encontr√≥ un error
	// El error ser√° un objeto de error
});
```

En este escenario, la funci√≥n `deleteMessages` retorna una promesa. El m√©todo `.then()` se ejecutar√° si la promesa se resuelve, y el m√©todo `.catch()` si la promesa se rechaza. En la funci√≥n `deleteMessages`, la promesa se resuelve luego de 2 segundos con la cadena de texto "Se han eliminado ${cantidad} mensajes.", as√≠ que el m√©todo `.catch()` nunca se ejecutar√°. Tambi√©n puedes pasar la funci√≥n `.catch()` como segundo par√°metro del `.then()`.

## ¬øC√≥mo implementar async/await?

### Teor√≠a

Es fundamental conocer la siguiente informaci√≥n antes de trabajar con async/await. Solo puedes usar la palabra clave `await` dentro de una funci√≥n declarada como` async` (Pones la palabra clave `async` antes de la palabra clave `function` o antes de los par√°metros cuando usas una funci√≥n `callback`).

Un ejemplo sencillo ser√≠a:

```js
async function declaredAsAsync() {
	// ...
}
```

O bien

```js
const declaredAsAsync = async () => {
	// ...
};
```

Tambi√©n se puede usar al declarar una funci√≥n flecha en un evento.

```js
client.on('event', async (first, last) => {
	// ...
});
```

Una dato importante a saber es que una funci√≥n declarada como `async` siempre devolver√° una promesa. Adem√°s de esto, si devuelve algo, la promesa se resolver√° con ese valor, y si arroja un error, rechazar√° la promesa con ese error.

### Ejecuci√≥n con c√≥digo de discord.js

Ahora que sabes c√≥mo funcionan las promesas y para qu√© se utilizan, veamos un ejemplo que maneja varias promesas. Digamos que quieres reaccionar con letras (indicadores regionales) en un orden espec√≠fico. Para este ejemplo, aqu√≠ hay una plantilla b√°sica para un bot de discord.js con algunos ajustes de ES6.

```js
const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

client.once('ready', () => {
	console.log('¬°Estoy listo!');
});

client.on('interactionCreate', interaction => {
	if (!interaction.isCommand()) return;

	if (interaction.commandName === 'react') {
		// ...
	}
});

client.login('tu-token-va-aqu√≠');
```

Si no sabes c√≥mo funciona la ejecuci√≥n asincr√≥nica de Node.js, probablemente intente algo como esto:

```js {4-7}
client.on('interactionCreate', interaction => {
	// ...
	if (commandName === 'react') {
		const message = interaction.reply('¬°Reaccionando!', { fetchReply: true });
		message.react('üá¶');
		message.react('üáß');
		message.react('üá®');
	}
});
```

Pero dado que todos estos m√©todos se inician al mismo tiempo, ser√≠a una carrera de cu√°l solicitud del servidor finaliz√≥ primero, por lo que no habr√≠a garant√≠a de que reaccionar√≠a en absoluto (si el mensaje no se recupera) o en el orden que quer√≠as. Para asegurarse de que reacciona despu√©s de que se env√≠a el mensaje y en orden (a, b, c), necesitar√≠as usar el `callback` del `.then()` de las promesas que estos m√©todos devuelven. El c√≥digo se ver√≠a as√≠:

```js {4-12}
client.on('interactionCreate', interaction => {
	// ...
	if (commandName === 'react') {
		interaction.reply('¬°Reaccionando!', { fetchReply: true })
			.then(message => {
				message.react('üá¶')
					.then(() => message.react('üáß'))
					.then(() => message.react('üá®'))
					.catch(error => {
						// manejar el error de cualquier rechazo de promesa aqu√≠
					});
			});
	}
});
```

En este fragmento de c√≥digo, las promesas se [resuelven en cadena](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#encadenamiento) entre s√≠, y si una de las promesas es rechazada, se llama a la funci√≥n `.catch()`. Aqu√≠ est√° el mismo c√≥digo pero con async/await:

```js {1,4-7}
client.on('interactionCreate', async interaction => {
	// ...
	if (commandName === 'react') {
		const message = await interaction.reply('¬°Reaccionando!', { fetchReply: true });
		await message.react('üá¶');
		await message.react('üáß');
		await message.react('üá®');
	}
});
```

Es principalmente el mismo c√≥digo, pero ¬øC√≥mo detectar√≠a los rechazos de las promesas ahora, ya que `.catch()` ya no est√°? Esa tambi√©n es una caracter√≠stica √∫til con `async`/`await`; el error se lanzar√° si lo espera para que pueda envolver las promesas esperadas dentro de un `try`/`catch`, y estar√° listo para comenzar.

```js {1,4-11}
client.on('interactionCreate', async interaction => {
	if (commandName === 'react') {
		try {
			const message = await interaction.reply('¬°Reaccionando!', { fetchReply: true });
			await message.react('üá¶');
			await message.react('üáß');
			await message.react('üá®');
		} catch (error) {
			// manejar el error de cualquier rechazo de promesa aqu√≠
		}
	}
});
```

Este c√≥digo se ve limpio y tambi√©n es f√°cil de leer.

Por lo tanto, es posible que se pregunte: "¬øC√≥mo obtendr√≠a el valor con el que se resolvi√≥ la promesa?".

Veamos un ejemplo en el que desea eliminar una respuesta enviada.

```js {3-9}
client.on('interactionCreate', interaction => {
	// ...
	if (commandName === 'delete') {
		interaction.reply('Este mensaje ser√° eliminado.', { fetchReply: true })
			.then(replyMessage => setTimeout(() => replyMessage.delete(), 10000))
			.catch(error => {
				// manejo del error
			});
	}
});
```

El valor de retorno de un `.reply()` con la opci√≥n `fetchReply` establecida en `true` es una promesa que se resuelve con la respuesta cuando se ha enviado, pero ¬øC√≥mo se ver√≠a el mismo c√≥digo con async/await?

```js {1,4-10}
client.on('interactionCreate', async interaction => {
	if (commandName === 'delete') {
		try {
			const replyMessage = await interaction.reply('Este mensaje ser√° eliminado.', { fetchReply: true });
			setTimeout(async () => replyMessage.delete(), 10000);
		} catch (error) {
			// manejo del error
		}
	}
});
```

Con `async`/`await` puedes asignar la funci√≥n esperada a una variable que represente el valor devuelto. Ahora ya sabes c√≥mo usar `async`/`await`.
